[package]
name = "fungible-token"
version = "1.0.0"
authors = [""]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0-pre.7"
near-contract-standards = "4.0.0-pre.7"
witgen = "0.14.0"

[dev-dependencies]
near-sdk-sim = "4.0.0-pre.7"
